server:
  port: 7902
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/quartz_db?characterEncoding=utf8&useSSL=false
    password: root
    username: root
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

logging:
  level:
    root: INFO

